import type { Metadata } from "next";
import { Poppins, Montserrat } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";

const poppins = Poppins({
  variable: "--font-poppins",
  weight:["400","600","700"]
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  weight:["400","600","700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${montserrat.variable} antialiased`}
      >
        <Header/>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
